### ISSUE TITLE
Need a basic login page that will check for authorization through GitHub API. 

### ISSUE THREAD

**Issue by Gutierrezjdr** [opensource-ny/OpenSource-NY#36]
Basic HTML needs a text box for username and password to use for authorization with GitHub API.

**Comment by zhik** [comment]
Let's not collect any passwords. Instead use [Github's built in Application OAuth](https://developer.github.com/v3/guides/basics-of-authentication/)

**Comment by yizongk** [comment]
The scope of this authorization is limited to accessing private repos. I think! Because the public repo will have their PR info public. I may be wrong, will see it as it comes up in the future.

**Comment by mxmsunny** [comment]
Should we still have a text box for the username?

**Comment by yizongk** [comment]
yes! We should still have a text box for username, but I would suggest holding that off til we get to the part where we actually need a box for the username for implementing our particular feature. Because right now, we don't really need it yet.

**Comment by mxmsunny** [comment]
okiedokie thanks!

**Comment by Fioringo** [comment]
As we agreed before, we don't want to collect passwords and other information about the users. Maybe down the road, but for right now I think we should just track all of the public pull requests and commits. This way we limit liability and can keep track of the scores easier.

This issue may be re-opened later on.
