### ISSUE TITLE
I want to make some changes on the git workflow

### ISSUE THREAD

**Issue by Gutierrezjdr** [opensource-ny/OpenSource-NY#64]
I have a different git workflow that stems from the pdf professor weiss put up 
[Git Workflow](https://github.com/hunter-college-ossd-spr19/github-workflow-activity-01/blob/master/github-workflow-presentation.pdf) .
I think @mxmsunny had some issues using the one in the readme as well.

**Comment by mxmsunny** [comment]
Yeah I had a slight issue with one part of it: 
![9E1920C4-708B-4BE4-BFE8-A137C3D4B4B5](https://user-images.githubusercontent.com/43188391/54838231-7a2faf80-4c9e-11e9-8ed1-713a5c454289.jpeg)

**Comment by yizongk** [comment]
Ahhhhh that part! 

I meant 
```
git pull upstream master        // This is the part where you fix any merge conflict before you git push to your fork's feature-branch
```

**Comment by yizongk** [comment]
So what do you have in mind to change in the README? Do a PR, and we can all check it!

**Comment by yizongk** [comment]
Fix and done. Thanks for those who helped!
