### ISSUE TITLE
Need a Rank System base off of the number of Successful PR

### ISSUE THREAD

**Issue by yizongk** [opensource-ny/OpenSource-NY#68]
Then output the ranking somewhere on the webpage

**Comment by Fioringo** [comment]
The success PR should mean almost nothing if it's not a big project. The larger the project, the heavier a successful PR should be. Let's pick a number of minimum contributors for the PR to be something, something medium weight, and something significant.

**Comment by yizongk** [comment]
Ya, you are right. I will make another PR to do just that. I meant this PR to just have a display board, a place for ranking to be displayed. My next PR would take into consideration of minimun # of contributors and maybe other factors.

**Comment by yizongk** [comment]
#69 fixed this
