### ISSUE TITLE
Trying to run the app on my desktop produces errors

### ISSUE THREAD

**Issue by stewartweiss** [opensource-ny/OpenSource-NY#81]
I cloned the application to my local machine and followed the instructions to install npm  and postgresql, after which I start up the server and the client. The instructions say to open localhost:3000 in the browser, but the server says it is listening to port 5000. Is this a mistake?

When the client starts, the errors are
```
./src/Components/PRdisplay.js
  Line 5:  'typeOf' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

Proxy error: Could not proxy request /sockjs-node/318/il3x3gy1/websocket from localhost:3000 to http://localhost:5000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
```

The window in Firefoz is unresponsive.

**Comment by Fioringo** [comment]
Hello,
It would seem that @Undid-Iridium 's database is not up. This should be changed to local mongo db either way. You can do that by changing the database connection configuration in `db.js` (located in `/myapp/server/src/db.js`). Main problem in this case is that you have to have mongoDB installed.
Download instructions can be found [here](https://docs.mongodb.com/manual/administration/install-on-linux/).

**Comment by yizongk** [comment]
I will take a look at this soon, I have been busy, but npm should have installed mongo db when you have done 'npm install'

**Comment by yizongk** [comment]
I am not able to reproduce this

**Comment by yizongk** [comment]
What OS is your machine?
