### ISSUE TITLE
PR list should really only update when user submits

### ISSUE THREAD

**Issue by yizongk** [opensource-ny/OpenSource-NY#89]
As of right now, the PR list auto refresh as you type, which could be nice for fast development.

But for user experience, it's horrible. When you type in the input box, it will brings up cached data that doesn't even relate to the current repo typed in the input box. And the PR list often jumps in and out of visibility. Not very nice UI. 

The PR list should always stay visible after the first search. And should only update on submit, and should not update on character keypress events etc (except the 'enter' key, which we count as submit)

**Comment by zhik** [comment]
Fixed #96

**Comment by yizongk** [comment]
Zhi, this one is not fixed yet. It's just the same behavior

**Comment by yizongk** [comment]
#98 Fixed this
