### ISSUE TITLE
Rank list starts count at zero

### ISSUE THREAD

**Issue by yizongk** [opensource-ny/OpenSource-NY#92]
the person with the most PRs on the ranking list, is currently listed like
0.
1.
2.
etc

Should really be like
1.
2.
3.
Counting starting at one

**Comment by rursteve2** [comment]
https://github.com/opensource-ny/OpenSource-NY/pull/93

**Comment by yizongk** [comment]
Hey stephen, the place you have made the change is at the constructor of RankElement.

I think we should leave the constructor alone, so that it constructs RankElement with values that you gave it as input.

I think you should move your fix to the place where RankElement is getting constructed. I am pretty it's in Ranks.js

In Ranks.js there's a place where RankElement is being created, that would be a good place to move your fix to. 

Thanks man!
